Repository maggiemccormick/Review-App, pull requests merged in 2020-12, with the labels that each got.

#2 gitflow-hotfix-stash: filePath
  best_flutter_ui_templates/lib/review_app/my_diary/meals_list_view.dart
Labels: bug

#6 Changed bottom nav bar
  lib/fitness_app/home_screen.dart
  lib/main.dart
  lib/model/homelist.dart
  lib/review_app/bottom_navigation_view/bottom_bar_view.dart
  lib/review_app/home_screen.dart
Labels: enhancement

#12 Fixed Workflow Actions
  .github/workflows/developmentChecks.yml
  .gitignore
  android/app/google-services.json
Labels: 👷 CI / DC
